### ISSUE TITLE
[PEGASUS and BART] summarization with csv dataset

### ISSUE THREAD

**Issue by SatishDeshbhratar** [robustness-gym/summvis#3]
Hi,

I have finetuned 2 models for text summarization, BART(facebook-bart) and PEGASUS(financial) and I have a dataset stored in .csv files. So, I want to use this tool for the analysis. 
Can you help me with this issue? How can I run this code for fine-tuned models and my dataset?

**Comment by jessevig** [comment]
Hi @SatishDeshbhratar, you will need to generate predictions from these models and then preprocess the data for the tool. The process is described in detail here: https://github.com/robustness-gym/summvis#get-your-data-into-summvis . Please let me know if you need any additional details or have followup questions.

**Comment by jessevig** [comment]
Hi @SatishDeshbhratar, FYI we've updated the code and README to make this a bit more straightforward: https://github.com/robustness-gym/summvis#loading-data-into-summvis . Please let me know if you have any issues. Thanks.

**Comment by jessevig** [comment]
Closing this issue for now, but feel free to reopen if you have additional questions.
