### ISSUE TITLE
summvis visualisation in scientific paper

### ISSUE THREAD

**Issue by LukasFides** [robustness-gym/summvis#5]
I wanted to know if there is already a way to export outputs displayed in the framework in order to e.g. show them in a text file (latex preferable). I assume the .cache folder hold necessary data (in the .dill files)? I wanted to ask prior to trying to extract the data on my own and I am happy to found this framework!

Cheers 
Lukas

**Comment by jessevig** [comment]
Hi @LukasFides, are you referring to exporting the underlying data used in the visualization, e.g. the alignments between the documents, or the visualizations themselves?

If it's the former, you can find the underlying data representation in the arguments to MainView here: https://github.com/robustness-gym/summvis/blob/65385cfabd7ceb62d2b58a0f66828b80038b80c8/summvis.py#L274

If you use the cache file as input, then the data is loaded here: https://github.com/robustness-gym/summvis/blob/65385cfabd7ceb62d2b58a0f66828b80038b80c8/summvis.py#L69. So you could try to replicate that function to export to your own custom file. Let me know if that makes sense.
