### ISSUE TITLE
":" on Windows can't be used in file names.

### ISSUE THREAD

**Issue by linkezh** [robustness-gym/summvis#6]
Hello, and thanks for your great work!
But I noticed that both in preprocessing and the main application, the default way to separate file names is ":", but it can not be used on Windows. After I downloaded your tool, the file names in `examples\wikinews\wikinews.cache\mgr\columns` became things like 'BertscoreAligner_spacy_document_spacy_summary_bart-cnndm', and so summvis can not find the file it needs (separated by ":"). Therefore, I can't even run this example in my PC.
Is there any way to solve it?
Thanks again!

**Comment by linkezh** [comment]
I found WSL could help me out. Thanks!

**Comment by gkiril** [comment]
@Zhao-Linke how did WSL help you? I tried to run it with WSL but I still got the same error
